services:
  mariner:
    container_name: mariner
    command: ["/usr/bin/mariner"]
    restart: unless-stopped

    ports:
      - "5000:5000"

    devices:
      - "/dev/serial0:/dev/serial0"

    volumes:
      - "/mnt/usb:/mnt/usb_share"
      - "./config.toml:/app/config.toml:ro"
