version: "3.8"

services:
  mariner:
    image: registry.intranet.suechting.com/mariner3d:latest
    container_name: mariner
    restart: unless-stopped

    command: ["/usr/bin/mariner"]

    ports:
      - "5000:5000"

    devices:
      - "/dev/ttyS0:/dev/ttyS0"

    volumes:
      - /mnt/usb:/mnt/usb_share
      - ./config.toml:/etc/mariner/config.toml:ro

    networks:
      - internal-net

networks:
  internal-net:
    external: true
